CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER PRIMARY KEY,
	NAME VARCHAR (50),
	EMAIL VARCHAR (100),
	ADDRESS_GEO_LAT FLOAT,
	ADDRESS_GEO_LNG FLOAT
);
CREATE TABLE IF NOT EXISTS ALBUMS (
	ID INTEGER PRIMARY KEY,
	USER_ID INTEGER,
	TITLE VARCHAR (200)
);
CREATE TABLE IF NOT EXISTS IMAGES (
	ID INTEGER PRIMARY KEY,
	ALBUM_ID INTEGER,
	TITLE VARCHAR (200) NOT NULL,
	URL VARCHAR (300)
);